;;; c64-theme.el --- A theme based on the Commodore64

;; Copyright (C) 2019-2020 Nahuel Jesús Sacchetti

;; Author: Nahuel Jesús Sacchetti <me@nsacchetti.com>
;; URL: http://github.com/elnawe/c64-theme
;; Package-Version: 20191208
;; Version: 1.0

;; This program is free software; you can redistribute it and/or modify it under
;; the terms of the GNU General Public License as published by the Free Software
;; Foundation, either version 3 of the License, or (at your option) any later
;; version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; A simple theme based on the Commodore64 and the QBasic editor. Emacs 24+
;; needed. This theme is only available for the X (GUI) version of Emacs.

;;; Credits:

;; Inspiration from http://www.ryocentral.info/2017/03/i3wm-as-c64-lookalike.html
;; Resources from https://www.c64-wiki.com/wiki/Color

;;; Code:

(deftheme c64 "The Commodore64 inspired color theme")

(defgroup c64-theme nil
  "Commodore64 theme."
  :group 'faces
  :prefix "c64-theme-"
  :link '(url-link :tag "GitHub" "https://github.com/elnawe/c64-theme")
  :tag "Commodore64 theme")

(defface org-bullets '()
  "Custom face to be used in `org-bullets-mode'. Use this face in
`org-bullets-face-name' to activate. "
  :group 'org-bullets-mode)

;;; Colors from: https://www.c64-wiki.com/wiki/Color

(defvar c64-colors-alist
  '(("c64-0"  . "#000000")   ; black
    ("c64-1"  . "#FFFFFF")   ; white
    ("c64-2"  . "#AA0000")   ; red
    ("c64-3"  . "#AAFFEE")   ; cyan
    ("c64-4"  . "#CC44CC")   ; violet
    ("c64-5"  . "#00CC55")   ; green
    ("c64-6"  . "#0000AA")   ; blue
    ("c64-7"  . "#EEEE77")   ; yellow
    ("c64-8"  . "#DD8855")   ; orange
    ("c64-9"  . "#664400")   ; brown
    ("c64-10" . "#FF7777")   ; light red
    ("c64-11" . "#333333")   ; dark grey
    ("c64-12" . "#777777")   ; grey
    ("c64-13" . "#AAFF66")   ; light green
    ("c64-14" . "#0088FF")   ; light blue
    ("c64-15" . "#BBBBBB"))  ; light grey
  "List of colors for the Commodore64 theme.")

(defmacro with-c64-color-variables (&rest body)
  "Binds all the colors from `c64-colors-alist' around
`body'. Use this macro to wrap the `custom-set-faces' in order to
access the `c64' theme color variables."
  (declare (indent 0))
  `(let (,@(mapcar (lambda (cons)
                     (list (intern (car cons)) (cdr cons)))
                   c64-colors-alist))
     ,@body))

;;; Theme

(with-c64-color-variables
 (custom-theme-set-faces
  'c64
   `(beacon-fallback-background ((t (:background ,c64-1 :foreground unspecified))))
   `(bold ((t (:background unspecified :bold t :foreground unspecified))))
   `(bold-italic ((t (:background unspecified :bold t :foreground unspecified :italic t))))
   `(bookmark-menu-bookmark ((t (:bold t))))
   `(bookmark-menu-heading ((t (:foreground ,c64-7))))
   `(border ((t (:foreground ,c64-1))))
   `(buffer-menu-buffer ((t (:bold t :foreground ,c64-1))))
   `(button ((t (:bold t :foreground ,c64-3 :underline nil))))
   `(calendar-month-header ((t (:foreground ,c64-1))))
   `(calendar-today ((t (:bold t :foreground ,c64-1))))
   `(calendar-weekday-header ((t (:foreground ,c64-1))))
   `(calendar-weekend-header ((t (:foreground ,c64-15))))
   `(comint-highlight-input ((t (:bold t :foreground ,c64-1))))
   `(comint-highlight-prompt ((t (:foreground ,c64-3))))
   `(company-echo ((t (:foreground ,c64-1))))
   `(company-echo-common ((t (:foreground ,c64-7))))
   `(company-preview ((t (:background unspecified :foreground ,c64-7))))
   `(company-preview-common ((t (:background unspecified :foreground ,c64-7))))
   `(company-preview-search ((t (:background ,c64-14 :foreground ,c64-1))))
   `(company-scrollbar-bg ((t (:background ,c64-12 :foreground ,c64-12))))
   `(company-scrollbar-fg ((t (:background ,c64-11 :foreground ,c64-11))))
   `(company-tooltip ((t (:background ,c64-15 :foreground ,c64-0))))
   `(company-tooltip-annotation ((t (:background unspecified :foreground ,c64-9))))
   `(company-tooltip-annotation-selection ((t (:background unspecified :foreground ,c64-9))))
   `(company-tooltip-common ((t (:background unspecified :foreground ,c64-11))))
   `(company-tooltip-common-selection ((t (:background unspecified :foreground ,c64-11))))
   `(company-tooltip-mouse ((t (:background ,c64-7))))
   `(company-tooltip-search ((t (:background ,c64-7))))
   `(company-tooltip-search-selection ((t (:background ,c64-7))))
   `(company-tooltip-selection ((t (:background ,c64-1))))
   `(compilation-column-number ((t (:foreground ,c64-15))))
   `(compilation-error ((t (:bold t :foreground ,c64-10))))
   `(compilation-info (( t (:bold t :foreground ,c64-5))))
   `(compilation-line-number ((t (:bold t :foreground ,c64-1))))
   `(compilation-mode-line-exit ((t (:bold t :foreground ,c64-5))))
   `(compilation-mode-line-fail ((t (:bold t :foreground ,c64-10))))
   `(compilation-mode-line-run ((t (:bold t :foreground ,c64-8))))
   `(compilation-warning ((t (:bold t :foreground ,c64-8))))
   `(completions-annotations ((t (:italic t))))
   `(completions-common-part ((t (:foreground ,c64-1))))
   `(completions-first-difference ((t (:bold t :foreground ,c64-1))))
   `(cursor ((t (:inherit default :inverse-video t))))
   `(custom-button
     ((t (:background ,c64-15 :box (:color ,c64-0 :line-width 2 :style released-button)
                      :foreground ,c64-0))))
   `(custom-button-mouse
     ((t (:background ,c64-1 :box (:color ,c64-0 :line-width 1 :style nil)
                      :foreground ,c64-0))))
   `(custom-button-pressed
     ((t (:background ,c64-15 :box (:color ,c64-0 :line-width 3 :style pressed-button)
                      :foreground ,c64-0))))
   `(custom-button-pressed-unraised
     ((t (:background unspecified :box nil :foreground ,c64-4 :underline t))))
   `(custom-button-unraised
     ((t (:background unspecified :box nil :foreground ,c64-1 :underline t))))
   `(custom-changed ((t (:background ,c64-14 :foreground ,c64-1))))
   `(custom-comment ((t (:background ,c64-12 :foreground ,c64-1))))
   `(custom-comment-tag ((t (:background unspecified :foreground ,c64-12))))
   `(custom-documentation ((t (:background unspecified :foreground ,c64-1))))
   `(custom-face-tag ((t (:background unspecified :bold t :foreground ,c64-3))))
   `(custom-group-subtitle ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(custom-group-tag ((t (:background unspecified :bold t :foreground ,c64-3 :height 150))))
   `(custom-group-tag-1 ((t (:background unspecified :bold t :foreground ,c64-10 :height 150))))
   `(custom-invalid ((t (:background ,c64-15 :foreground ,c64-2))))
   `(custom-link ((t (:background unspecified :foreground ,c64-3 :underline t))))
   `(custom-modified ((t (:background ,c64-14 :foreground ,c64-1))))
   `(custom-rogue ((t (:background ,c64-0 :foreground ,c64-8))))
   `(custom-saved ((t (:background unspecified :foreground ,c64-15 :underline t))))
   `(custom-set ((t (:background ,c64-1 :foreground ,c64-6))))
   `(custom-state ((t (:background unspecified :foreground ,c64-5))))
   `(custom-themed ((t (:background ,c64-14 :foreground ,c64-1))))
   `(custom-variable-button
     ((t (:background unspecified :bold t :foreground ,c64-1 :underline t))))
   `(custom-variable-tag ((t (:background unspecified :bold t :foreground ,c64-3))))
   `(custom-visibility
     ((t (:background unspecified :foreground ,c64-14 :height 90 :underline t))))
   `(dashboard-banner-logo-title ((t (:background unspecified :foreground ,c64-1 :height 140))))
   `(dashboard-footer ((t (:background unspecified :foreground ,c64-15))))
   `(dashboard-heading ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(dashboard-navigator ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(dashboard-text-banner ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(default ((t (:background ,c64-6 :foreground ,c64-1))))
   `(diary ((t (:background unspecified :foreground ,c64-7))))
   `(diary-anniversary ((t (:background unspecified :bold t :foreground ,c64-7))))
   `(diary-button
     ((t (:background ,c64-15 :box (:color ,c64-0) :foreground ,c64-0))))
   `(diary-time ((t (:background unspecified :foreground ,c64-1))))
   `(diff-added ((t (:background ,c64-13 :foreground ,c64-0))))
   `(diff-changed ((t (:background unspecified :foreground ,c64-1))))
   `(diff-context ((t (:background unspecified :foreground ,c64-15))))
   `(diff-file-header ((t (:background ,c64-15 :bold t :foreground ,c64-1))))
   `(diff-function ((t (:background ,c64-12 :foreground ,c64-1))))
   `(diff-header ((t (:background ,c64-12 :foreground ,c64-1))))
   `(diff-hunk-header ((t (:background ,c64-12 :foreground ,c64-1))))
   `(diff-index ((t (:background ,c64-15 :bold t :foreground ,c64-1))))
   `(diff-indicator-added ((t (:background ,c64-13 :foreground ,c64-0))))
   `(diff-indicator-changed ((t (:background unspecified :foreground ,c64-1))))
   `(diff-indicator-removed ((t (:background ,c64-10 :foreground ,c64-0))))
   `(diff-nonexistent ((t (:background ,c64-15 :bold t :foreground ,c64-1))))
   `(diff-refine-added ((t (:background ,c64-13 :foreground ,c64-0))))
   `(diff-refine-changed ((t (:background ,c64-7 :foreground ,c64-0))))
   `(diff-refine-removed ((t (:background ,c64-10 :foreground ,c64-0))))
   `(diff-removed ((t (:background ,c64-10 :foreground ,c64-0))))
   `(dired-directory ((t (:background ,c64-1 :bold t :foreground ,c64-6))))
   `(dired-flagged ((t (:background unspecified :bold t :foreground ,c64-7))))
   `(dired-header ((t (:background unspecified :bold t :foreground ,c64-5 :height 130))))
   `(dired-ignored ((t (:background unspecified :foreground ,c64-15))))
   `(dired-mark ((t (:background unspecified :foreground ,c64-4))))
   `(dired-marked ((t (:background unspecified :bold t :foreground ,c64-4))))
   `(dired-perm-write ((t (:background unspecified :foreground ,c64-14))))
   `(dired-symlink ((t (:background unspecified :bold nil :foreground ,c64-1 :italic t))))
   `(dired-warning ((t (:background unspecified :bold t :foreground ,c64-10))))
   `(eldoc-highlight-function-argument ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(epa-field-body ((t (:background unspecified :foreground ,c64-3 :italic t))))
   `(epa-field-name ((t (:background unspecified :bold t :foreground ,c64-3))))
   `(epa-mark ((t (:background unspecified :bold t :foreground ,c64-4))))
   `(epa-string ((t (:background unspecified :foreground ,c64-1))))
   `(epa-validity-disabled ((t (:background ,c64-15 :foreground ,c64-11 :italic t))))
   `(epa-validity-high ((t (:background unspecified :bold t :foreground ,c64-3))))
   `(epa-validity-low ((t (:background unspecified :foreground ,c64-1 :italic t))))
   `(epa-validity-medium ((t (:background unspecified :foreground ,c64-3 :italic t))))
   `(error ((t (:background unspecified :bold t :foreground ,c64-10))))
   `(escape-glyph ((t (:background unspecified :foreground ,c64-3))))
   `(fancy-battery-charging ((t (:background ,c64-5 :bold t :foreground ,c64-0))))
   `(fancy-battery-critical ((t (:background ,c64-10 :bold t :foreground ,c64-0))))
   `(fancy-battery-discharging ((t (:background unspecified :foreground unspecified))))
   `(file-name-shadow ((t (:background unspecified :foreground ,c64-15))))
   `(fixed-pitch ((t (:background unspecified :foreground ,c64-1))))
   `(fixed-pitch-serif ((t (:background unspecified :family "Monospace Serif" :foreground ,c64-1))))
   `(flyspell-duplicate ((t (:background unspecified :foreground unspecified :underline (:color ,c64-10 :style wave)))))
   `(flyspell-incorrect ((t (:background unspecified :foreground unspecified :underline (:color ,c64-10 :style wave)))))
   `(font-lock-builtin-face ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(font-lock-comment-delimiter-face ((t (:background unspecified :foreground ,c64-5))))
   `(font-lock-comment-face ((t (:background unspecified :foreground ,c64-5))))
   `(font-lock-constant-face ((t (:background unspecified :foreground ,c64-3))))
   `(font-lock-doc-face ((t (:background unspecified :foreground ,c64-15))))
   `(font-lock-function-name-face ((t (:background unspecified :foreground ,c64-1))))
   `(font-lock-keyword-face ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(font-lock-negation-char-face ((t (:background unspecified :foreground ,c64-10))))
   `(font-lock-preprocessor-face ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(font-lock-regexp-grouping-backslash ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(font-lock-regexp-grouping-construct ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(font-lock-string-face ((t (:background unspecified :foreground ,c64-15))))
   `(font-lock-type-face ((t (:background unspecified :foreground ,c64-13))))
   `(font-lock-variable-name-face ((t (:background unspecified :foreground ,c64-1))))
   `(font-lock-warning-face ((t (:background unspecified :bold t :foreground ,c64-10))))
   `(fringe ((t (:background ,c64-6 :foreground ,c64-0))))
   `(glyphless-char ((t (:background unspecified :foreground unspecified :height 80))))
   `(gnus-button ((t (:background unspecified :bold t :foreground unspecified))))
   `(gnus-emphasis-bold ((t (:background unspecified :bold t :foreground unspecified))))
   `(gnus-emphasis-bold-italic ((t (:background unspecified :bold t :foreground unspecified :italic t))))
   `(gnus-emphasis-highlight-words ((t (:background ,c64-7 :foreground ,c64-0))))
   `(gnus-emphasis-italic ((t (:background unspecified :foreground unspecified :italic t))))
   `(gnus-emphasis-strikethru ((t (:background unspecified :foreground unspecified :strike-through t))))
   `(gnus-emphasis-underline ((t (:background unspecified :foreground unspecified :underline t))))
   `(gnus-emphasis-underline-bold ((t (:background unspecified :bold t :foreground unspecified :underline t))))
   `(gnus-emphasis-underline-bold-italic ((t (:background unspecified :bold t :foreground unspecified :italic t :underline t))))
   `(gnus-emphasis-underline-italic ((t (:background unspecified :foreground unspecified :italic t :underline t))))
   `(gnus-group-mail-1 ((t (:background unspecified :bold t :foreground ,c64-7))))
   `(gnus-group-mail-1-empty ((t (:background unspecified :foreground ,c64-7))))
   `(gnus-group-mail-2 ((t (:background unspecified :bold t :foreground ,c64-13))))
   `(gnus-group-mail-2-empty ((t (:background unspecified :foreground ,c64-13))))
   `(gnus-group-mail-3 ((t (:background unspecified :bold t :foreground ,c64-3))))
   `(gnus-group-mail-3-empty ((t (:background unspecified :foreground ,c64-3))))
   `(gnus-group-mail-low ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(gnus-group-mail-low-empty ((t (:background unspecified :foreground ,c64-1))))
   `(gnus-group-news-1 ((t (:background unspecified :bold t :foreground ,c64-7))))
   `(gnus-group-news-1-empty ((t (:background unspecified :foreground ,c64-7))))
   `(gnus-group-news-2 ((t (:background unspecified :bold t :foreground ,c64-13))))
   `(gnus-group-news-2-empty ((t (:background unspecified :foreground ,c64-13))))
   `(gnus-group-news-3 ((t (:background unspecified :bold t :foreground ,c64-3))))
   `(gnus-group-news-3-empty ((t (:background unspecified :foreground ,c64-3))))
   `(gnus-group-news-4 ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(gnus-group-news-4-empty ((t (:background unspecified :foreground ,c64-1))))
   `(gnus-group-news-5 ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(gnus-group-news-5-empty ((t (:background unspecified :foreground ,c64-1))))
   `(gnus-group-news-6 ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(gnus-group-news-6-empty ((t (:background unspecified :foreground ,c64-1))))
   `(gnus-group-news-low ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(gnus-group-news-low-empty ((t (:background unspecified :foreground ,c64-1))))
   `(gnus-header-content ((t (:background unspecified :foreground ,c64-15 :italic t))))
   `(gnus-header-from ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(gnus-header-name ((t (:background unspecified :bold t :foreground ,c64-15))))
   `(gnus-header-newsgroups ((t (:background unspecified :foreground ,c64-7 :italic t))))
   `(gnus-header-subject ((t (:background unspecified :bold t :foreground ,c64-3))))
   `(gnus-server-agent ((t (:background unspecified :foreground ,c64-14))))
   `(gnus-server-closed ((t (:background unspecified :foreground ,c64-15 :italic t))))
   `(gnus-server-cloud ((t (:background unspecified :bold t :foreground ,c64-13))))
   `(gnus-server-cloud-host ((t (:background ,c64-13 :foreground ,c64-6 :italic t))))
   `(gnus-server-denied ((t (:background unspecified :bold t :foreground ,c64-10))))
   `(gnus-server-offline ((t (:background unspecified :bold t :foreground ,c64-12))))
   `(gnus-server-opened ((t (:background unspecified :bold t :foreground ,c64-13))))
   `(gnus-signature ((t (:background unspecified :foreground ,c64-15))))
   `(gnus-splash ((t (:background unspecified :foreground ,c64-15))))
   `(gnus-summary-cancelled ((t (:background ,c64-0 :foreground ,c64-7))))
   `(gnus-summary-high-ancient ((t (:background unspecified :bold t :foreground ,c64-14))))
   `(gnus-summary-high-read ((t (:background unspecified :bold t :foreground ,c64-13))))
   `(gnus-summary-high-ticked ((t (:background unspecified :bold t :foreground ,c64-7))))
   `(gnus-summary-high-undownloaded ((t (:background unspecified :bold t :foreground ,c64-15))))
   `(gnus-summary-high-unread ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(gnus-summary-low-ancient ((t (:background unspecified :foreground ,c64-14 :italic t))))
   `(gnus-summary-low-read ((t (:background unspecified :foreground ,c64-13 :italic t))))
   `(gnus-summary-low-ticked ((t (:background unspecified :foreground ,c64-7 :italic t))))
   `(gnus-summary-low-undownloaded ((t (:background unspecified :foreground ,c64-15 :italic t))))
   `(gnus-summary-low-unread ((t (:background unspecified :foreground ,c64-1 :italic t))))
   `(gnus-summary-normal-ancient ((t (:background unspecified :foreground ,c64-14))))
   `(gnus-summary-normal-read ((t (:background unspecified :foreground ,c64-13))))
   `(gnus-summary-normal-ticked ((t (:background unspecified :foreground ,c64-7))))
   `(gnus-summary-normal-undownloaded ((t (:background unspecified :foreground ,c64-15))))
   `(gnus-summary-normal-unread ((t (:background unspecified :foreground ,c64-1))))
   `(gnus-summary-selected ((t (:background unspecified :foreground unspecified :underline t))))
   `(header-line ((t (:background ,c64-6 :foreground ,c64-1))))
   `(header-line-highlight ((t (:background ,c64-7 :foreground ,c64-0))))
   `(helm-M-x-key ((t (:background unspecified :foreground ,c64-13 :underline t))))
   `(helm-action ((t (:background unspecified :foreground ,c64-1 :underline t))))
   `(helm-bookmark-addressbook ((t (:background unspecified :foreground ,c64-7))))
   `(helm-bookmark-directory ((t (:inherit dired-directory))))
   `(helm-bookmark-file ((t (:background unspecified :foreground ,c64-7))))
   `(helm-bookmark-file-not-found ((t (:background unspecified :foreground ,c64-15))))
   `(helm-bookmark-gnus ((t (:background unspecified :foreground ,c64-4))))
   `(helm-bookmark-info ((t (:background unspecified :foreground ,c64-13))))
   `(helm-bookmark-man ((t (:background unspecified :foreground ,c64-8))))
   `(helm-bookmark-w3m ((t (:background unspecified :foreground ,c64-14))))
   `(helm-buffer-archive ((t (:background unspecified :foreground ,c64-8))))
   `(helm-buffer-directory ((t (:inherit dired-directory))))
   `(helm-buffer-file ((t (:background unspecified :bold nil :foreground ,c64-1))))
   `(helm-buffer-modified ((t (:background unspecified :bold nil :foreground ,c64-13))))
   `(helm-buffer-not-saved ((t (:background unspecified :foreground ,c64-10))))
   `(helm-buffer-process ((t (:background unspecified :foreground ,c64-14))))
   `(helm-buffer-saved-out ((t (:background ,c64-0 :foreground ,c64-10))))
   `(helm-buffer-size ((t (:background unspecified :foreground ,c64-4))))
   `(helm-candidate-number ((t (:background ,c64-15 :bold t :foreground ,c64-0))))
   `(helm-candidate-number-suspended ((t (:bold t :inherit mode-line-inactive))))
   `(helm-delete-async-message ((t (:background unspecified :foreground ,c64-7))))
   `(helm-eob-line ((t (:background unspecified :foreground ,c64-1))))
   `(helm-etags-file ((t (:background unspecified :foreground ,c64-12 :underline t))))
   `(helm-ff-denied ((t (:background ,c64-0 :foreground ,c64-10))))
   `(helm-ff-directory ((t (:inherit dired-directory))))
   `(helm-ff-dirs ((t (:inherit default))))
   `(helm-ff-dotted-directory ((t (:background unspecified :foreground ,c64-15))))
   `(helm-ff-dotted-symlink-directory ((t (:background ,c64-15 :foreground ,c64-11))))
   `(helm-ff-executable ((t (:background unspecified :foreground ,c64-13))))
   `(helm-ff-file ((t (:background unspecified :bold nil :foreground ,c64-1))))
   `(helm-ff-invalid-symlink ((t (:background ,c64-2 :foreground ,c64-1))))
   `(helm-ff-pipe ((t (:background ,c64-0 :foreground ,c64-7))))
   `(helm-ff-prefix ((t (:background ,c64-7 :foreground ,c64-0))))
   `(helm-ff-socket ((t (:background unspecified :foreground ,c64-10))))
   `(helm-ff-suid ((t (:background ,c64-10 :foreground ,c64-1))))
   `(helm-ff-symlink ((t (:background unspecified :foreground ,c64-1 :italic t))))
   `(helm-ff-truename ((t (:background unspecified :foreground ,c64-15))))
   `(helm-grep-cmd-line ((t (:background unspecified :foreground ,c64-15))))
   `(helm-grep-file ((t (:backgound unspecified :foreground ,c64-7 :underline t))))
   `(helm-grep-finish ((t (:background unspecified :foreground ,c64-13))))
   `(helm-grep-lineno ((t (:backgound unspecified :foreground ,c64-8))))
   `(helm-grep-match ((t (:background unspecified :foreground ,c64-7))))
   `(helm-header ((t (:background unspecified :foreground ,c64-1))))
   `(helm-header-line-left-margin ((t (:background ,c64-7 :foreground ,c64-0))))
   `(helm-helper ((t (:background unspecified :foreground unspecified))))
   `(helm-history-delete ((t (:background ,c64-10 :foreground ,c64-1))))
   `(helm-history-remote ((t (:background unspecified :foreground ,c64-4))))
   `(helm-lisp-completion-info ((t (:background unspecified :foreground ,c64-10))))
   `(helm-lisp-show-completion ((t (:background ,c64-11 :foreground ,c64-1))))
   `(helm-locate-finish ((t (:background unspecified :foreground ,c64-13))))
   `(helm-match ((t (:background unspecified :foreground ,c64-5))))
   `(helm-match-item ((t (:background ,c64-10 :foreground ,c64-2))))
   `(helm-minibuffer-prompt ((t (:background unspecified :foreground ,c64-3))))
   `(helm-moccur-buffer ((t (:background unspecified :foreground ,c64-3 :underline t))))
   `(helm-mode-prefix ((t (:background ,c64-2 :foreground ,c64-1))))
   `(helm-non-file-buffer ((t (:background unspecified :foreground ,c64-15 :italic t))))
   `(helm-prefarg ((t (:background unspecified :foreground ,c64-13))))
   `(helm-resume-need-update ((t (:background ,c64-10 :foreground ,c64-0))))
   `(helm-selection ((t (:background ,c64-1 :bold t :foreground ,c64-0))))
   `(helm-selection-line ((t (:background ,c64-12 :foreground ,c64-1))))
   `(helm-separator ((t (:background unspecified :foreground ,c64-10))))
   `(helm-source-header ((t (:background ,c64-11 :box nil :foreground ,c64-1 :height 130))))
   `(helm-visible-mark ((t (:background ,c64-13 :foreground ,c64-0))))
   `(helm-argument-name ((t (:background unspecified :foreground unspecified :italic t))))
   `(hi-black-b ((t (:background unspecified :bold t :foreground unspecified))))
   `(hi-black-hb ((t (:background unspecified :bold t :foreground unspecified :height 150))))
   `(hi-blue ((t (:background ,c64-14 :foreground ,c64-0))))
   `(hi-blue-b ((t (:background unspecified :foreground ,c64-14))))
   `(hi-green ((t (:background ,c64-5 :foreground ,c64-0))))
   `(hi-green-b ((t (:background unspecified :foreground ,c64-5))))
   `(hi-pink ((t (:background ,c64-10 :foreground ,c64-0))))
   `(hi-red-b ((t (:background unspecified :foreground ,c64-10))))
   `(hi-yellow ((t (:background ,c64-7 :foreground ,c64-0))))
   `(highlight ((t (:background ,c64-1 :foreground ,c64-6))))
   `(hl-line ((t (:background ,c64-1 :foreground ,c64-6))))
   `(holiday ((t (:background ,c64-9 :foreground ,c64-1))))
   `(homoglyph ((t (:background unspecified :foreground ,c64-3))))
   `(ibuffer-locked-buffer ((t (:background unspecified :foreground ,c64-8))))
   `(internal-border ((t (:background unspecified :foreground ,c64-1))))
   `(isearch ((t (:background ,c64-13 :foreground ,c64-6))))
   `(isearch-fail ((t (:background ,c64-2 :foreground ,c64-1))))
   `(italic ((t (:background unspecified :foreground unspecified :italic t))))
   `(lazy-highlight ((t (:background ,c64-12 :foreground ,c64-1))))
   `(line-number ((t (:background unspecified :foreground ,c64-15))))
   `(line-number-current-line ((t (:background unspecified :foreground ,c64-1))))
   `(link ((t (:background unspecified :foreground ,c64-3 :underline t))))
   `(link-visited ((t (:background unspecified :foreground ,c64-4 :underline t))))
   `(linum ((t (:background ,c64-6 :foreground ,c64-1))))
   `(match ((t (:background ,c64-13 :foreground ,c64-0))))
   `(menu ((t (:background unspecified :foreground ,c64-1))))
   `(message-cited-text ((t (:background unspecified :foreground ,c64-15 :italic t))))
   `(message-header-cc (( t (:background unspecified :foreground ,c64-1))))
   `(message-header-name ((t (:background unspecified :bold t :foreground ,c64-15))))
   `(message-header-newsgroups ((t (:background unspecified :foreground ,c64-7 :italic t))))
   `(message-header-other ((t (:background unspecified :foreground ,c64-15))))
   `(message-header-subject ((t (:background unspecified :bold t :foreground ,c64-3))))
   `(message-header-to ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(message-header-xheader ((t (:background unspecified :foreground ,c64-14))))
   `(message-mml ((t (:background unspecified :foreground ,c64-8))))
   `(message-separator ((t (:background unspecified :foreground ,c64-5))))
   `(minibuffer-prompt ((t (:background unspecified :bold t :foreground ,c64-3))))
   `(mm-command-output ((t (:background unspecified :foreground ,c64-5))))
   `(mm-uu-extract ((t (:background ,c64-5 :foreground ,c64-1))))
   `(mode-line
     ((t (:background ,c64-15 :box (:color ,c64-15 :line-width 2)
                      :foreground ,c64-0))))
   `(mode-line-buffer-id ((t (:background unspecified :bold t :foreground unspecified))))
   `(mode-line-emphasis ((t (:background unspecified :bold t :foreground unspecified))))
   `(mode-line-highlight ((t (:background ,c64-7 :bold t :foreground ,c64-0))))
   `(mode-line-inactive
     ((t (:background ,c64-11 :box (:color ,c64-11 :line-width 2)
                      :foreground ,c64-1))))
   `(mouse ((t (:inherit default))))
   `(mouse-drag-and-drop-region ((t (:inherit default :inverse-video t))))
   `(next-error ((t (:inherit error :inverse-video t))))
   `(nobreak-hyphen ((t (:background unspecified :foreground ,c64-3))))
   `(nobreak-space ((t (:background unspecified :foreground ,c64-3 :underline t))))

   `(org-agenda-calendar-event ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(org-agenda-calendar-sexp ((t (:background unspecified :foreground unspecified))))
   `(org-agenda-clocking
     ((t (:background ,c64-7 :box (:color ,c64-7 :line-width 3)
                      :distant-foreground ,c64-0 :foreground ,c64-0))))
   `(org-agenda-column-dateline ((t (:background ,c64-12 :foreground ,c64-1))))
   `(org-agenda-current-time ((t (:background unspecified :foreground ,c64-1 :italic t))))
   `(org-agenda-date ((t (:background unspecified :bold t :foreground ,c64-3))))
   `(org-agenda-date-today ((t (:height 140 :inherit org-agenda-date))))
   `(org-agenda-date-weekend ((t (:bold nil :inherit org-agenda-date))))
   `(org-agenda-diary ((t (:background unspecified :foreground ,c64-1))))
   `(org-agenda-dimmed-todo-face ((t (:background unspecified :foreground ,c64-12))))
   `(org-agenda-done ((t (:background unspecified :foreground ,c64-5 :strike-through t))))
   `(org-agenda-filter-category ((t (:background ,c64-15 :foreground ,c64-0))))
   `(org-agenda-filter-effort ((t (:background ,c64-15 :foreground ,c64-0))))
   `(org-agenda-filter-regexp ((t (:background ,c64-15 :foreground ,c64-0))))
   `(org-agenda-filter-tags ((t (:background ,c64-15 :foreground ,c64-0))))
   `(org-agenda-restriction-lock ((t (:background ,c64-0 :foreground ,c64-1))))
   `(org-agenda-structure ((t (:background unspecified :foreground ,c64-14 :height 180))))
   `(org-archived ((t (:background unspecified :foreground ,c64-12))))
   `(org-block ((t (:foreground ,c64-15))))
   `(org-block-begin-line ((t (:foreground ,c64-14))))
   `(org-block-end-line ((t (:foreground ,c64-14))))
   `(org-bullets ((t (:height 60 :inherit default))))
   `(org-checkbox ((t (:background ,c64-14 :bold t :foreground ,c64-1))))
   `(org-checkbox-statistics-done ((t (:background ,c64-5 :bold t :foreground ,c64-1))))
   `(org-checkbox-statistics-todo ((t (:background ,c64-2 :bold t :foreground ,c64-1))))
   `(org-clock-overlay ((t (:background ,c64-14 :foreground ,c64-1))))
   `(org-code ((t (:background unspecified :foreground ,c64-15))))
   `(org-column ((t (:background ,c64-11 :foreground ,c64-1))))
   `(org-column-title ((t (:background ,c64-11 :bold t :foreground ,c64-1 :underline t))))
   `(org-date ((t (:background unspecified :foreground ,c64-15))))
   `(org-date-selected ((t (:background ,c64-3 :foreground ,c64-0))))
   `(org-default ((t (:background unspecified :foreground ,c64-15))))
   `(org-document-info ((t (:background unspecified :foreground ,c64-15))))
   `(org-document-info-keyword ((t (:background unspecified :foreground ,c64-3))))
   `(org-document-title ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(org-done ((t (:background unspecified :bold t :foreground ,c64-5))))
   `(org-drawer ((t (:background unspecified :foreground ,c64-3))))
   `(org-ellipsis ((t (:background unspecified :foreground ,c64-15 :underline nil))))
   `(org-footnote ((t (:background unspecified :foreground ,c64-3 :underline t))))
   `(org-formula ((t (:background unspecified :foreground ,c64-8))))
   `(org-headline-done ((t (:background unspecified :foreground ,c64-15 :strike-through t))))
   `(org-hide ((t (:background ,c64-6 :foreground ,c64-6))))
   `(org-indent ((t (:background ,c64-6 :foreground ,c64-6))))
   `(org-latex-and-related ((t (:background unspecified :foreground ,c64-8))))
   `(org-level-1 ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(org-level-2 ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(org-level-3 ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(org-level-4 ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(org-level-5 ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(org-level-6 ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(org-level-7 ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(org-level-8 ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(org-link ((t (:background unspecified :foreground ,c64-3 :underline t))))
   `(org-list-dt ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(org-macro ((t (:background unspecified :foreground ,c64-8))))
   `(org-meta-line ((t (:background unspecified :foreground ,c64-15))))
   `(org-mode-line-clock ((t (:inherit mode-line))))
   `(org-mode-line-clock-overrun
     ((t (:background ,c64-2 :box (:color ,c64-2) :foreground ,c64-1
                      :inherit mode-line))))
   `(org-priority ((t (:background unspecified :bold t :foreground ,c64-7))))
   `(org-property-value ((t (:background unspecified :foreground ,c64-15))))
   `(org-quote ((t (:background unspecified :foreground ,c64-15))))
   `(org-recur ((t (:background unspecified :bold t :box t :foreground ,c64-15))))
   `(org-scheduled ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(org-scheduled-previously ((t (:background unspecified :bold t :foreground ,c64-10))))
   `(org-scheduled-today ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(org-sexp-date ((t (:inherit org-date))))
   `(org-special-keyword ((t (:background unspecified :foreground ,c64-5))))
   `(org-super-agenda-header ((t (:inherit org-agenda-structure))))
   `(org-table ((t (:background unspecified :foreground ,c64-5))))
   `(org-tag ((t (:background unspecified :bold nil :foreground ,c64-5))))
   `(org-tag-group ((t (:inherit org-tag))))
   `(org-target ((t (:background unspecified :foreground ,c64-1 :underline t))))
   `(org-time-grid ((t (:background unspecified :foreground ,c64-15))))
   `(org-todo ((t (:background unspecified :bold t :foreground ,c64-10))))
   `(org-upcoming-deadline ((t (:background unspecified :foreground ,c64-10))))
   `(org-verbatim ((t (:background unspecified :bold t :foreground ,c64-15))))
   `(org-verse ((t (:background unspecified :foreground ,c64-15))))
   `(org-warning ((t (:background unspecified :bold t :foreground ,c64-10))))
   `(outline-1 ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(outline-2 ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(outline-3 ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(outline-4 ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(outline-5 ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(outline-6 ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(outline-7 ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(outline-8 ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(package-description ((t (:background unspecified :foreground ,c64-1))))
   `(package-help-section-name ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(package-name ((t (:background unspecified :foreground ,c64-3 :underline t))))
   `(package-status-avail-obso ((t (:background unspecified :bold t :foreground ,c64-10))))
   `(package-status-available ((t (:background unspecified :foreground ,c64-1))))
   `(package-status-built-in ((t (:background unspecified :bold t :foreground ,c64-15))))
   `(package-status-dependency ((t (:background unspecified :foreground ,c64-5))))
   `(package-status-disabled ((t (:background ,c64-15 :bold t :foreground ,c64-2))))
   `(package-status-external ((t (:background unspecified :bold t :foreground ,c64-7))))
   `(package-status-held ((t (:background unspecified :foreground ,c64-4))))
   `(package-status-incompat ((t (:background ,c64-10 :bold t :foreground ,c64-0))))
   `(package-status-installed ((t (:background ,c64-5 :foreground ,c64-1))))
   `(package-status-new ((t (:background unspecified :foreground ,c64-13 :italic t))))
   `(package-status-unsigned ((t (:background unspecified :foreground ,c64-10 :italic t))))
   `(page-break-lines ((t (:background unspecified :foreground ,c64-15))))
   `(query-replace ((t (:inherit isearch))))
   `(read-multiple-choice-face ((t (:background unspecified :bold t :foreground ,c64-1))))
   `(region ((t (:background unspecified :extend t :foreground unspecified :inverse-video t))))
   `(rmail-header-name ((t (:inherit default))))
   `(rmail-highlight ((t (:inherit default :inverse-video t))))
   `(scroll-bar ((t (:inherit default))))
   `(secondary-selection ((t (:background ,c64-12 :foreground ,c64-1))))
   `(shadow ((t (:background unspecified :foreground ,c64-12))))
   `(show-paren-match ((t (:background unspecified :bold t :foreground ,c64-5))))
   `(show-paren-match-expression ((t (:inherit show-paren-match))))
   `(show-paren-mismatch ((t (:background unspecified :bold t :foreground ,c64-10))))
   `(success ((t (:background unspecified :bold t :foreground ,c64-13))))
   `(term ((t (:background unspecified :foreground ,c64-1))))
   `(term-bold ((t (:background unspecified :bold t :foreground unspecified))))
   `(term-color-black ((t (:background ,c64-0 :foreground ,c64-0))))
   `(term-color-blue ((t (:background ,c64-6 :foreground ,c64-6))))
   `(term-color-cyan ((t (:background ,c64-3 :foreground ,c64-3))))
   `(term-color-green ((t (:background ,c64-5 :foreground ,c64-5))))
   `(term-color-magenta ((t (:background ,c64-4 :foreground ,c64-4))))
   `(term-color-red ((t (:background ,c64-2 :foreground ,c64-2))))
   `(term-color-white ((t (:background ,c64-1 :foreground ,c64-1))))
   `(term-color-yellow ((t (:background ,c64-7 :foreground ,c64-7))))
   `(term-underline ((t (:background unspecified :foreground unspecified :underline t))))
   `(tool-bar ((t (:background ,c64-12 :foreground ,c64-0))))
   `(tooltip ((t (:background ,c64-15 :foreground ,c64-0))))
   `(trailing-whitespace ((t (:background ,c64-2 :foreground ,c64-1))))
   `(underline ((t (:background unspecified :foreground unspecified :underline t))))
   `(variable-pitch ((t (:background unspecified :family "Sans Serif" :foreground unspecified))))
   `(vertical-border ((t (:background unspecified :foreground ,c64-1))))
   `(warning ((t (:background unspecified :bold t :foreground ,c64-10))))
   `(whitespace-trailing ((t (:background ,c64-2 :foreground ,c64-1))))
   `(window-divider ((t (:background unspecified :foreground ,c64-15))))
   `(window-divider-first-pixel ((t (:background unspecified :foreground ,c64-12))))
   `(window-divider-last-pixel ((t (:background unspecified :foreground ,c64-11))))))
